import type { Metadata } from "next";
import { Geist, Geist_Mono, Cormorant_Garamond } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { WindowSizeProvider } from "@/app/providers";
import localFont from "next/font/local"


const neue = localFont({
  src: "../fonts/neue.otf",
  variable: '--font-neue'
})

const neuebold = localFont({
  src: "../fonts/neuebold.otf",
  variable: '--font-neuebold'
})
const neuebolditalic = localFont({
  src: "../fonts/neuebolditalic.otf",
  variable: '--font-neuebolditalic'
})
const neueitalic = localFont({
  src: "../fonts/neueitalic.otf",
  variable: '--font-neueitalic'
})

const neueitaliclight = localFont({
  src: "../fonts/neuelightitalic.otf",
  variable: '--font-neueitaliclight'
})

const neuemedium = localFont({
  src: "../fonts/neuemedium.otf",
  variable: '--font-neuemedium'
})

const neuemediumitlaic = localFont({
  src: "../fonts/neuemediumitalic.otf",
  variable: '--font-neuemediumitlaic'
})

const baflion = localFont({
  src: "../fonts/baflion.otf",
  variable: '--font-baflion'
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cormorantGaramond = Cormorant_Garamond({
  variable: "--font-cormorant-garamond",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const baflionSans = localFont({
  src: "../fonts/BaflionSans-Black.otf",
  variable: "--font-baflion-sans",
  display: "swap",
});

const neueMontreal = localFont({
  src: [
    {
      path: "../fonts/NeueMontreal-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/NeueMontreal-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/NeueMontreal-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/NeueMontreal-Italic.otf",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-neue-montreal",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${neue.variable} ${neuebold.variable} ${neuebolditalic.variable} ${neueitalic.variable} ${neueitaliclight.variable} ${neuemedium.variable} ${neuemediumitlaic.variable} ${baflion.variable} ${geistSans.variable} ${geistMono.variable} ${cormorantGaramond.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <WindowSizeProvider>
          {children}
        </WindowSizeProvider>
      </body>
    </html>
  );
}
